#!/usr/bin/env node
/**
 * M18, Trivia dataset expansion: 210 → 500+ questions across 10 categories
 * (the PRD's 500+ target; owner request: "much much larger dataset and add
 * genres"). Existing questions are kept verbatim; new ones are appended and
 * the result is written to BOTH the client dataset (solo play + local daily
 * fallback) and the server dataset (daily seeding + room mode). Idempotent.
 *
 * Run: node scripts/generate-trivia.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** [category, question, [optionA, optionB, optionC, optionD], answerIndex] */
const NEW_QUESTIONS = [
  // ------------------------------ General ------------------------------
  ['General', 'How many continents are there on Earth?', ['5', '6', '7', '8'], 2],
  [
    'General',
    'What is the largest ocean on Earth?',
    ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    3,
  ],
  ['General', 'How many colors are in a rainbow?', ['5', '6', '7', '8'], 2],
  ['General', 'What is the capital of Australia?', ['Sydney', 'Melbourne', 'Canberra', 'Perth'], 2],
  ['General', 'Which instrument has 88 keys?', ['Violin', 'Piano', 'Guitar', 'Flute'], 1],
  ['General', 'What do bees produce?', ['Milk', 'Honey', 'Wax only', 'Silk'], 1],
  ['General', 'How many minutes are in a day?', ['1,200', '1,440', '1,600', '1,800'], 1],
  [
    'General',
    'What is the hardest natural substance?',
    ['Iron', 'Quartz', 'Diamond', 'Granite'],
    2,
  ],
  [
    'General',
    'Which planet is known as the Red Planet?',
    ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    1,
  ],
  ['General', 'What do you call a baby kangaroo?', ['Cub', 'Joey', 'Calf', 'Kit'], 1],
  ['General', 'How many players are on a soccer team?', ['9', '10', '11', '12'], 2],
  ['General', 'What is the freezing point of water in Celsius?', ['0', '32', '100', '-10'], 0],
  ['General', 'Which country has the most people?', ['USA', 'India', 'China', 'Indonesia'], 1],
  [
    'General',
    'What is the tallest mountain on Earth?',
    ['K2', 'Kangchenjunga', 'Everest', 'Kilimanjaro'],
    2,
  ],
  ['General', 'How many teeth does a human adult normally have?', ['28', '30', '32', '34'], 2],
  ['General', 'What is the currency of Japan?', ['Won', 'Yuan', 'Yen', 'Ringgit'], 2],
  [
    'General',
    'Which animal is the fastest land animal?',
    ['Lion', 'Cheetah', 'Horse', 'Greyhound'],
    1,
  ],
  [
    'General',
    'What gas do plants absorb from the air?',
    ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    2,
  ],
  ['General', 'How many bones are in the adult human body?', ['186', '206', '226', '246'], 1],
  [
    'General',
    'Which is the largest desert on Earth?',
    ['Sahara', 'Gobi', 'Antarctic', 'Kalahari'],
    2,
  ],
  [
    'General',
    'What is the smallest country in the world?',
    ['Monaco', 'Malta', 'Vatican City', 'San Marino'],
    2,
  ],
  [
    'General',
    'Which language has the most native speakers?',
    ['English', 'Spanish', 'Hindi', 'Mandarin'],
    3,
  ],
  ['General', 'What do you call a group of lions?', ['Herd', 'Pride', 'Pack', 'Flock'], 1],
  ['General', 'How many sides does a hexagon have?', ['5', '6', '7', '8'], 1],
  [
    'General',
    'Which metal is liquid at room temperature?',
    ['Mercury', 'Aluminum', 'Lead', 'Zinc'],
    0,
  ],
  [
    'General',
    'What is the national animal of Australia?',
    ['Koala', 'Kangaroo', 'Emu', 'Dingo'],
    1,
  ],
  [
    'General',
    'Which fruit has its seeds on the outside?',
    ['Apple', 'Orange', 'Strawberry', 'Grapes'],
    2,
  ],
  [
    'General',
    'What is the speed of light roughly?',
    ['300,000 km/s', '150,000 km/s', '1,000 km/s', '30,000 km/s'],
    0,
  ],
  ['General', 'How many hearts does an octopus have?', ['1', '2', '3', '4'], 2],
  [
    'General',
    'Which country is famous for the Great Barrier Reef?',
    ['Brazil', 'Mexico', 'Australia', 'Thailand'],
    2,
  ],
  // ------------------------------ Science ------------------------------
  ['Science', 'What is the chemical symbol for gold?', ['Go', 'Gd', 'Au', 'Ag'], 2],
  ['Science', 'Which planet has the most moons?', ['Earth', 'Mars', 'Saturn', 'Neptune'], 2],
  ['Science', 'What is H2O?', ['Salt', 'Water', 'Oxygen', 'Hydrogen peroxide'], 1],
  [
    'Science',
    'Which force pulls objects toward Earth?',
    ['Magnetism', 'Friction', 'Gravity', 'Inertia'],
    2,
  ],
  [
    'Science',
    'What is the powerhouse of the cell?',
    ['Nucleus', 'Ribosome', 'Mitochondria', 'Membrane'],
    2,
  ],
  ['Science', 'How many planets are in our solar system?', ['7', '8', '9', '10'], 1],
  ['Science', 'What is the largest planet?', ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], 2],
  [
    'Science',
    'What gas do humans need to breathe?',
    ['Nitrogen', 'Carbon dioxide', 'Oxygen', 'Helium'],
    2,
  ],
  [
    'Science',
    'What is the boiling point of water at sea level?',
    ['90°C', '100°C', '110°C', '120°C'],
    1,
  ],
  ['Science', 'Which vitamin comes from sunlight?', ['A', 'B12', 'C', 'D'], 3],
  ['Science', 'What is the smallest unit of life?', ['Atom', 'Cell', 'Molecule', 'Tissue'], 1],
  [
    'Science',
    'Which scientist proposed the theory of relativity?',
    ['Newton', 'Einstein', 'Hawking', 'Bohr'],
    1,
  ],
  [
    'Science',
    'What is the most abundant gas in Earth’s atmosphere?',
    ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    2,
  ],
  ['Science', 'How many chromosomes do humans have?', ['23', '44', '46', '48'], 2],
  [
    'Science',
    'What is the study of weather called?',
    ['Geology', 'Meteorology', 'Astronomy', 'Ecology'],
    1,
  ],
  [
    'Science',
    'Which part of the eye controls how much light enters?',
    ['Retina', 'Cornea', 'Iris', 'Lens'],
    2,
  ],
  ['Science', 'What is the fastest land animal?', ['Cheetah', 'Leopard', 'Pronghorn', 'Lion'], 0],
  ['Science', 'Which element has the symbol Fe?', ['Fluorine', 'Iron', 'Francium', 'Lead'], 1],
  ['Science', 'What is the main ingredient in glass?', ['Sand', 'Clay', 'Limestone', 'Soda'], 0],
  [
    'Science',
    'Which organ pumps blood around the body?',
    ['Lungs', 'Liver', 'Heart', 'Kidneys'],
    2,
  ],
  [
    'Science',
    'What do we call a scientist who studies stars?',
    ['Geologist', 'Astronomer', 'Meteorologist', 'Seismologist'],
    1,
  ],
  ['Science', 'Which planet is closest to the Sun?', ['Venus', 'Earth', 'Mars', 'Mercury'], 3],
  [
    'Science',
    'What is the largest organ of the human body?',
    ['Liver', 'Brain', 'Skin', 'Lungs'],
    2,
  ],
  [
    'Science',
    'How many bones does a baby have at birth?',
    ['About 200', 'About 300', 'About 400', 'About 100'],
    1,
  ],
  ['Science', 'Which of these is NOT a state of matter?', ['Solid', 'Liquid', 'Gas', 'Energy'], 3],
  [
    'Science',
    'What causes tides on Earth?',
    ['Wind', 'The Moon’s gravity', 'Earthquakes', 'Ocean currents alone'],
    1,
  ],
  [
    'Science',
    'Which acid is found in the human stomach?',
    ['Citric acid', 'Hydrochloric acid', 'Acetic acid', 'Sulfuric acid'],
    1,
  ],
  ['Science', 'What is the SI unit of force?', ['Watt', 'Joule', 'Newton', 'Pascal'], 2],
  ['Science', 'Which animal can regenerate lost limbs?', ['Dog', 'Starfish', 'Shark', 'Eagle'], 1],
  [
    'Science',
    'What is the process of plants making food called?',
    ['Respiration', 'Photosynthesis', 'Fermentation', 'Digestion'],
    1,
  ],
  // ------------------------------ History ------------------------------
  ['History', 'In which year did World War II end?', ['1943', '1944', '1945', '1946'], 2],
  [
    'History',
    'Who was the first President of the United States?',
    ['Lincoln', 'Jefferson', 'Washington', 'Adams'],
    2,
  ],
  ['History', 'The Great Wall is in which country?', ['Japan', 'China', 'India', 'Mongolia'], 1],
  [
    'History',
    'Who discovered the sea route to India in 1498?',
    ['Columbus', 'Magellan', 'Vasco da Gama', 'Marco Polo'],
    2,
  ],
  [
    'History',
    'The pyramids of Giza are in which country?',
    ['Mexico', 'Egypt', 'Peru', 'Sudan'],
    1,
  ],
  [
    'History',
    'Who was known as the Iron Lady?',
    ['Indira Gandhi', 'Margaret Thatcher', 'Angela Merkel', 'Golda Meir'],
    1,
  ],
  ['History', 'In which year did India gain independence?', ['1945', '1946', '1947', '1948'], 2],
  [
    'History',
    'Who was the first man to walk on the Moon?',
    ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Michael Collins'],
    2,
  ],
  ['History', 'The Roman Colosseum is in which city?', ['Athens', 'Rome', 'Naples', 'Florence'], 1],
  [
    'History',
    'Who painted the Mona Lisa?',
    ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'],
    2,
  ],
  ['History', 'The Berlin Wall fell in which year?', ['1987', '1988', '1989', '1990'], 2],
  [
    'History',
    'Who was the first woman Prime Minister of India?',
    ['Sonia Gandhi', 'Indira Gandhi', 'Sarojini Naidu', 'Pratibha Patil'],
    1,
  ],
  ['History', 'Which empire built Machu Picchu?', ['Aztec', 'Maya', 'Inca', 'Olmec'], 2],
  [
    'History',
    'Who was the leader of Nazi Germany?',
    ['Mussolini', 'Hitler', 'Stalin', 'Franco'],
    1,
  ],
  ['History', 'The Titanic sank in which year?', ['1905', '1910', '1912', '1915'], 2],
  [
    'History',
    'Who wrote the Indian national anthem?',
    ['Rabindranath Tagore', 'Bankim Chandra Chatterjee', 'Sarojini Naidu', 'Subhash Chandra Bose'],
    0,
  ],
  [
    'History',
    'Which ancient wonder stood in Alexandria?',
    ['The Colossus', 'The Lighthouse', 'The Hanging Gardens', 'The Temple of Artemis'],
    1,
  ],
  [
    'History',
    'Who was assassinated on 30 January 1948?',
    ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Bhagat Singh', 'Subhash Chandra Bose'],
    1,
  ],
  ['History', 'The first moon landing was in which year?', ['1965', '1967', '1969', '1971'], 2],
  [
    'History',
    'Which city was the capital of the Byzantine Empire?',
    ['Rome', 'Athens', 'Constantinople', 'Alexandria'],
    2,
  ],
  [
    'History',
    'Who was known as the Father of the Atomic Bomb?',
    ['Einstein', 'Oppenheimer', 'Fermi', 'Teller'],
    1,
  ],
  ['History', 'The French Revolution began in which year?', ['1776', '1789', '1799', '1804'], 1],
  [
    'History',
    'Which queen ruled England for 63 years (1837-1901)?',
    ['Elizabeth I', 'Victoria', 'Anne', 'Mary'],
    1,
  ],
  [
    'History',
    'The Silk Road connected China with which region?',
    ['Africa', 'Europe', 'Australia', 'South America'],
    1,
  ],
  [
    'History',
    'Who was the first emperor of Rome?',
    ['Julius Caesar', 'Nero', 'Augustus', 'Constantine'],
    2,
  ],
  ['History', 'In which year did the American Civil War end?', ['1863', '1864', '1865', '1867'], 2],
  [
    'History',
    'The Taj Mahal was built by which emperor?',
    ['Akbar', 'Shah Jahan', 'Aurangzeb', 'Babur'],
    1,
  ],
  [
    'History',
    'Which explorer first circumnavigated the globe?',
    ['Columbus', 'Cook', 'Magellan’s crew', 'Drake'],
    2,
  ],
  ['History', 'The UN was founded in which year?', ['1943', '1945', '1948', '1950'], 1],
  [
    'History',
    'Which civilization built the city of Petra?',
    ['Romans', 'Nabataeans', 'Greeks', 'Phoenicians'],
    1,
  ],
  // --------------------------- Pop Culture ------------------------------
  [
    'Pop Culture',
    'Which singer is known as the Queen of Pop?',
    ['Beyoncé', 'Madonna', 'Rihanna', 'Taylor Swift'],
    1,
  ],
  [
    'Pop Culture',
    'Which TV show is set in the office of Dunder Mifflin?',
    ['Parks and Recreation', 'The Office', 'Community', '30 Rock'],
    1,
  ],
  [
    'Pop Culture',
    'Who played Iron Man in the MCU?',
    ['Chris Evans', 'Robert Downey Jr.', 'Mark Ruffalo', 'Chris Hemsworth'],
    1,
  ],
  [
    'Pop Culture',
    'Which movie features the quote “May the Force be with you”?',
    ['Star Trek', 'Star Wars', 'Guardians of the Galaxy', 'Dune'],
    1,
  ],
  [
    'Pop Culture',
    'Who is known as the King of Pop?',
    ['Elvis Presley', 'Michael Jackson', 'Prince', 'Justin Timberlake'],
    1,
  ],
  [
    'Pop Culture',
    'Which band sang “Bohemian Rhapsody”?',
    ['The Beatles', 'Queen', 'Pink Floyd', 'Led Zeppelin'],
    1,
  ],
  [
    'Pop Culture',
    'In which year did the first iPhone launch?',
    ['2005', '2006', '2007', '2008'],
    2,
  ],
  [
    'Pop Culture',
    'Who is the protagonist of the Harry Potter series?',
    ['Ron Weasley', 'Hermione Granger', 'Harry Potter', 'Neville Longbottom'],
    2,
  ],
  [
    'Pop Culture',
    'Which streaming platform produced “Stranger Things”?',
    ['Netflix', 'Hulu', 'Amazon Prime', 'Disney+'],
    0,
  ],
  [
    'Pop Culture',
    'What is the name of the green ogre in the Shrek movies?',
    ['Donkey', 'Shrek', 'Fiona', 'Farquaad'],
    1,
  ],
  [
    'Pop Culture',
    'Who won the first season of “Kaun Banega Crorepati”?',
    ['Harshvardhan Nawathe', 'Rahul Mahajan', 'Amitabh Bachchan', 'Sushil Kumar'],
    0,
  ],
  [
    'Pop Culture',
    'Which artist released the album “Thriller”?',
    ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Lionel Richie'],
    1,
  ],
  [
    'Pop Culture',
    'Which fictional detective lives at 221B Baker Street?',
    ['Hercule Poirot', 'Sherlock Holmes', 'Miss Marple', 'Columbo'],
    1,
  ],
  [
    'Pop Culture',
    'What is the name of the supercomputer in “2001: A Space Odyssey”?',
    ['HAL', 'WALL-E', 'JARVIS', 'GERTY'],
    0,
  ],
  [
    'Pop Culture',
    'Which game franchise features Mario?',
    ['Sonic', 'Super Mario', 'Zelda', 'Crash Bandicoot'],
    1,
  ],
  [
    'Pop Culture',
    'Who hosted “The Oprah Winfrey Show”?',
    ['Oprah Winfrey', 'Ellen DeGeneres', 'Kelly Ripa', 'Barbara Walters'],
    0,
  ],
  [
    'Pop Culture',
    'Which superhero wears a red and blue suit with a spider emblem?',
    ['Batman', 'Superman', 'Spider-Man', 'Iron Man'],
    2,
  ],
  [
    'Pop Culture',
    'What is the name of the wizarding school in Harry Potter?',
    ['Beauxbatons', 'Hogwarts', 'Durmstrang', 'Ilvermorny'],
    1,
  ],
  [
    'Pop Culture',
    'Which singer is nicknamed “The Weekend”?',
    ['The Weeknd', 'Post Malone', 'Drake', 'Bruno Mars'],
    0,
  ],
  [
    'Pop Culture',
    'Which movie series features the character Jack Sparrow?',
    ['Indiana Jones', 'Pirates of the Caribbean', 'The Mummy', 'National Treasure'],
    1,
  ],
  [
    'Pop Culture',
    'Who created the character Mickey Mouse?',
    ['Walt Disney', 'Steven Spielberg', 'Hanna-Barbera', 'Chuck Jones'],
    0,
  ],
  [
    'Pop Culture',
    'Which reality show features the quote “You’re fired!”?',
    ['Survivor', 'Big Brother', 'The Apprentice', 'Shark Tank'],
    2,
  ],
  [
    'Pop Culture',
    'What is the fastest-selling album by Taylor Swift?',
    ['Red', '1989', 'Midnights', 'Folklore'],
    2,
  ],
  [
    'Pop Culture',
    'Which movie won Best Picture at the 2020 Oscars?',
    ['Joker', 'Parasite', '1917', 'Once Upon a Time in Hollywood'],
    1,
  ],
  [
    'Pop Culture',
    'Who is the CEO of Tesla?',
    ['Jeff Bezos', 'Elon Musk', 'Tim Cook', 'Sundar Pichai'],
    1,
  ],
  [
    'Pop Culture',
    'Which animated movie features the song “Let It Go”?',
    ['Moana', 'Tangled', 'Frozen', 'Encanto'],
    2,
  ],
  [
    'Pop Culture',
    'What is the name of the coffee shop in “Friends”?',
    ['Central Perk', 'The Coffee Bean', 'Java Joe', 'Monk’s Cafe'],
    0,
  ],
  [
    'Pop Culture',
    'Who played Jack in the movie “Titanic”?',
    ['Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Johnny Depp'],
    1,
  ],
  ['Pop Culture', 'Which K-pop group sang “Dynamite”?', ['BLACKPINK', 'BTS', 'EXO', 'TWICE'], 1],
  [
    'Pop Culture',
    'What is the name of the wizard in “The Lord of the Rings”?',
    ['Gandalf', 'Dumbledore', 'Merlin', 'Radagast'],
    0,
  ],
  // ------------------------------ Sports --------------------------------
  ['Sports', 'How many players are on a cricket team?', ['10', '11', '12', '9'], 1],
  [
    'Sports',
    'Which country hosted the 2024 Summer Olympics?',
    ['Japan', 'France', 'USA', 'Australia'],
    1,
  ],
  [
    'Sports',
    'In which sport would you perform a slam dunk?',
    ['Volleyball', 'Tennis', 'Basketball', 'Handball'],
    2,
  ],
  [
    'Sports',
    'How often is the FIFA World Cup held?',
    ['Every 2 years', 'Every 4 years', 'Every 5 years', 'Every 6 years'],
    1,
  ],
  [
    'Sports',
    'Who has won the most Grand Slam singles titles (men)?',
    ['Federer', 'Nadal', 'Djokovic', 'Sampras'],
    2,
  ],
  ['Sports', 'Which sport is played at Wimbledon?', ['Golf', 'Tennis', 'Cricket', 'Badminton'], 1],
  ['Sports', 'How many points is a touchdown worth in American football?', ['3', '6', '7', '8'], 1],
  [
    'Sports',
    'Which country won the 2011 Cricket World Cup?',
    ['Australia', 'Sri Lanka', 'India', 'Pakistan'],
    2,
  ],
  [
    'Sports',
    'In which sport do players use a shuttlecock?',
    ['Squash', 'Badminton', 'Tennis', 'Table tennis'],
    1,
  ],
  [
    'Sports',
    'Who is the fastest man in history (100m record)?',
    ['Tyson Gay', 'Usain Bolt', 'Carl Lewis', 'Yohan Blake'],
    1,
  ],
  [
    'Sports',
    'Which team has won the most NBA championships?',
    ['Lakers', 'Celtics', 'Bulls', 'Warriors'],
    1,
  ],
  ['Sports', 'How many holes are on a standard golf course?', ['9', '12', '18', '24'], 2],
  [
    'Sports',
    'Which boxer was known as “The Greatest”?',
    ['Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'Joe Frazier'],
    1,
  ],
  [
    'Sports',
    'In which year did India win its first T20 World Cup?',
    ['2005', '2007', '2009', '2011'],
    1,
  ],
  ['Sports', 'Which country invented cricket?', ['India', 'Australia', 'England', 'Pakistan'], 2],
  ['Sports', 'How many players are on a basketball team?', ['4', '5', '6', '7'], 1],
  [
    'Sports',
    'Which F1 driver has won the most championships?',
    ['Schumacher & Hamilton (7 each)', 'Senna', 'Verstappen', 'Vettel'],
    0,
  ],
  ['Sports', 'What is the diameter of a basketball hoop in inches?', ['16', '18', '20', '24'], 1],
  [
    'Sports',
    'Which country has won the most FIFA World Cups?',
    ['Germany', 'Italy', 'Brazil', 'Argentina'],
    2,
  ],
  [
    'Sports',
    'In which sport is the “butterfly” a stroke?',
    ['Rowing', 'Swimming', 'Kayaking', 'Sailing'],
    1,
  ],
  [
    'Sports',
    'Who is known as the “Flying Sikh”?',
    ['Milkha Singh', 'Usain Bolt', 'PT Usha', 'Abhinav Bindra'],
    0,
  ],
  [
    'Sports',
    'How long is a marathon in kilometers?',
    ['40.2 km', '42.2 km', '44.2 km', '38.2 km'],
    1,
  ],
  [
    'Sports',
    'Which Indian city hosted the 2010 Commonwealth Games?',
    ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
    1,
  ],
  ['Sports', 'Which sport uses a puck?', ['Field hockey', 'Ice hockey', 'Lacrosse', 'Rugby'], 1],
  ['Sports', 'Who won the 2023 FIFA Women’s World Cup?', ['USA', 'Spain', 'England', 'Japan'], 1],
  ['Sports', 'How many overs are in a T20 cricket match (per side)?', ['10', '15', '20', '50'], 2],
  [
    'Sports',
    'Which tennis player is nicknamed “The King of Clay”?',
    ['Federer', 'Djokovic', 'Nadal', 'Murray'],
    2,
  ],
  [
    'Sports',
    'In which year were the first modern Olympics held?',
    ['1892', '1896', '1900', '1904'],
    1,
  ],
  [
    'Sports',
    'Which Indian cricketer scored 100 international centuries?',
    ['Virat Kohli', 'Rahul Dravid', 'Sachin Tendulkar', 'Sourav Ganguly'],
    2,
  ],
  ['Sports', 'Which country invented table tennis?', ['China', 'Japan', 'England', 'USA'], 2],
  // ----------------------------- Geography ------------------------------
  [
    'Geography',
    'What is the capital of Canada?',
    ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
    2,
  ],
  [
    'Geography',
    'Which is the longest river in the world?',
    ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    1,
  ],
  [
    'Geography',
    'Mount Everest is on the border of which two countries?',
    ['India & China', 'Nepal & China', 'Nepal & India', 'China & Bhutan'],
    1,
  ],
  [
    'Geography',
    'Which country is shaped like a boot?',
    ['Greece', 'Spain', 'Italy', 'Portugal'],
    2,
  ],
  ['Geography', 'What is the largest country by area?', ['Canada', 'China', 'USA', 'Russia'], 3],
  [
    'Geography',
    'Which is the smallest continent?',
    ['Europe', 'Australia', 'Antarctica', 'South America'],
    1,
  ],
  [
    'Geography',
    'The Sahara Desert is in which continent?',
    ['Asia', 'Africa', 'Australia', 'South America'],
    1,
  ],
  ['Geography', 'What is the capital of Japan?', ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], 2],
  ['Geography', 'Which ocean is the deepest?', ['Atlantic', 'Indian', 'Arctic', 'Pacific'], 3],
  ['Geography', 'Which river flows through Paris?', ['Thames', 'Rhine', 'Seine', 'Loire'], 2],
  [
    'Geography',
    'What is the capital of Brazil?',
    ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    2,
  ],
  [
    'Geography',
    'Which is the largest island in the world?',
    ['Madagascar', 'Borneo', 'Greenland', 'Sumatra'],
    2,
  ],
  [
    'Geography',
    'The Statue of Liberty is in which city?',
    ['Washington DC', 'Boston', 'New York', 'Philadelphia'],
    2,
  ],
  ['Geography', 'Which country has the most time zones?', ['Russia', 'USA', 'France', 'China'], 2],
  ['Geography', 'What is the capital of Italy?', ['Milan', 'Venice', 'Rome', 'Naples'], 2],
  [
    'Geography',
    'Which is the highest waterfall in the world?',
    ['Niagara', 'Angel Falls', 'Victoria', 'Iguazu'],
    1,
  ],
  [
    'Geography',
    'The Ganges river flows mainly through which country?',
    ['Bangladesh', 'Nepal', 'India', 'Bhutan'],
    2,
  ],
  ['Geography', 'What is the capital of Egypt?', ['Alexandria', 'Giza', 'Cairo', 'Luxor'], 2],
  [
    'Geography',
    'Which two countries share the longest border?',
    ['USA & Mexico', 'Canada & USA', 'China & Russia', 'India & China'],
    1,
  ],
  [
    'Geography',
    'Which city is known as the City of Love?',
    ['Rome', 'Paris', 'Vienna', 'Prague'],
    1,
  ],
  [
    'Geography',
    'Which country is the largest producer of coffee?',
    ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'],
    2,
  ],
  ['Geography', 'What is the capital of Germany?', ['Munich', 'Hamburg', 'Berlin', 'Frankfurt'], 2],
  [
    'Geography',
    'Which desert is the largest hot desert?',
    ['Gobi', 'Kalahari', 'Sahara', 'Arabian'],
    2,
  ],
  [
    'Geography',
    'The Eiffel Tower was built for which event?',
    ['Olympics', 'World’s Fair of 1889', 'World War I', 'Expo 1900'],
    1,
  ],
  [
    'Geography',
    'Which country has the most volcanoes?',
    ['Japan', 'Indonesia', 'USA', 'Iceland'],
    1,
  ],
  [
    'Geography',
    'What is the capital of Russia?',
    ['St. Petersburg', 'Moscow', 'Kiev', 'Novosibirsk'],
    1,
  ],
  [
    'Geography',
    'Which is the largest lake in the world?',
    ['Lake Superior', 'Caspian Sea', 'Lake Victoria', 'Lake Baikal'],
    1,
  ],
  [
    'Geography',
    'Which continent is the Amazon rainforest in?',
    ['Africa', 'Asia', 'South America', 'Central America'],
    2,
  ],
  [
    'Geography',
    'Which country is known as the Land of the Rising Sun?',
    ['China', 'Japan', 'Thailand', 'South Korea'],
    1,
  ],
  ['Geography', 'What is the capital of Spain?', ['Barcelona', 'Seville', 'Madrid', 'Valencia'], 2],
  // ------------------------------ Movies --------------------------------
  ['Movies', 'Who directed “Inception”?', ['Spielberg', 'Nolan', 'Tarantino', 'Scorsese'], 1],
  [
    'Movies',
    'Which movie won the first-ever Academy Award for Best Picture?',
    ['Gone with the Wind', 'Wings', 'The Jazz Singer', 'Citizen Kane'],
    1,
  ],
  [
    'Movies',
    'Who played the Joker in “The Dark Knight”?',
    ['Jack Nicholson', 'Heath Ledger', 'Jared Leto', 'Joaquin Phoenix'],
    1,
  ],
  [
    'Movies',
    'Which studio produced “Toy Story”?',
    ['DreamWorks', 'Pixar', 'Blue Sky', 'Illumination'],
    1,
  ],
  [
    'Movies',
    'What is the highest-grossing film of all time (unadjusted)?',
    ['Avatar', 'Titanic', 'Avengers: Endgame', 'Star Wars: The Force Awakens'],
    0,
  ],
  [
    'Movies',
    'Who directed “Schindler’s List”?',
    ['Spielberg', 'Kubrick', 'Coppola', 'Hitchcock'],
    0,
  ],
  [
    'Movies',
    'Which movie features the line “I’m the king of the world!”?',
    ['Avatar', 'Titanic', 'Braveheart', 'Gladiator'],
    1,
  ],
  ['Movies', 'Who played Forrest Gump?', ['Tom Hanks', 'Tom Cruise', 'Brad Pitt', 'Matt Damon'], 0],
  [
    'Movies',
    'Which film series features the character Darth Vader?',
    ['Star Trek', 'Star Wars', 'The Matrix', 'Alien'],
    1,
  ],
  [
    'Movies',
    'Who directed “Pulp Fiction”?',
    ['Tarantino', 'Scorsese', 'Fincher', 'Coen Brothers'],
    0,
  ],
  [
    'Movies',
    'Which animated film features the character Elsa?',
    ['Moana', 'Frozen', 'Tangled', 'Coco'],
    1,
  ],
  [
    'Movies',
    'Who played Neo in “The Matrix”?',
    ['Keanu Reeves', 'Brad Pitt', 'Will Smith', 'Johnny Depp'],
    0,
  ],
  [
    'Movies',
    'Which movie series follows a boy wizard?',
    ['Percy Jackson', 'Harry Potter', 'Narnia', 'Eragon'],
    1,
  ],
  ['Movies', 'Who directed “The Godfather”?', ['Scorsese', 'Coppola', 'Lumet', 'Penn'], 1],
  [
    'Movies',
    'Which 2023 film starred Margot Robbie as a famous doll?',
    ['Oppenheimer', 'Barbie', 'Wonka', 'The Little Mermaid'],
    1,
  ],
  [
    'Movies',
    'Who is the voice of Woody in “Toy Story”?',
    ['Tim Allen', 'Tom Hanks', 'Billy Crystal', 'Robin Williams'],
    1,
  ],
  [
    'Movies',
    'Which movie introduced the character James Bond?',
    ['Goldfinger', 'Dr. No', 'From Russia with Love', 'Thunderball'],
    1,
  ],
  [
    'Movies',
    'Who starred in “Cast Away” and “Forrest Gump”?',
    ['Tom Hanks', 'Will Smith', 'Jim Carrey', 'Morgan Freeman'],
    0,
  ],
  [
    'Movies',
    'Which director is known for “Taxi Driver” and “Goodfellas”?',
    ['Tarantino', 'Scorsese', 'Spielberg', 'De Palma'],
    1,
  ],
  [
    'Movies',
    'Which movie’s theme song is “My Heart Will Go On”?',
    ['Titanic', 'Romeo + Juliet', 'The Bodyguard', 'Pearl Harbor'],
    0,
  ],
  [
    'Movies',
    'Who played Black Panther in the MCU?',
    ['Chadwick Boseman', 'Michael B. Jordan', 'Idris Elba', 'John Boyega'],
    0,
  ],
  [
    'Movies',
    'Which film won Best Picture at the 2024 Oscars?',
    ['Barbie', 'Oppenheimer', 'Killers of the Flower Moon', 'Poor Things'],
    1,
  ],
  ['Movies', 'Who directed “Jaws” and “E.T.”?', ['Lucas', 'Spielberg', 'Zemeckis', 'Cameron'], 1],
  [
    'Movies',
    'Which movie series features the character Gandalf?',
    ['Narnia', 'Harry Potter', 'The Lord of the Rings', 'The Hobbit only'],
    2,
  ],
  [
    'Movies',
    'Who played Captain Jack Sparrow?',
    ['Johnny Depp', 'Orlando Bloom', 'Hugh Jackman', 'Colin Farrell'],
    0,
  ],
  [
    'Movies',
    'Which 2019 movie won Best Picture?',
    ['Joker', '1917', 'Parasite', 'Once Upon a Time in Hollywood'],
    2,
  ],
  ['Movies', 'Who directed “Interstellar”?', ['Nolan', 'Villeneuve', 'Scott', 'Cameron'], 0],
  [
    'Movies',
    'Which film features the character Michael Corleone?',
    ['Goodfellas', 'The Godfather', 'Scarface', 'Casino'],
    1,
  ],
  [
    'Movies',
    'Who voiced the Genie in the 1992 “Aladdin”?',
    ['Robin Williams', 'Eddie Murphy', 'Mike Myers', 'Will Smith'],
    0,
  ],
  [
    'Movies',
    'Which movie was the first to gross $1 billion?',
    ['Titanic', 'Jurassic Park', 'The Lion King', 'Star Wars'],
    0,
  ],
  // ------------------------------ Music ----------------------------------
  [
    'Music',
    'Who sang “Billie Jean”?',
    ['Prince', 'Michael Jackson', 'Stevie Wonder', 'James Brown'],
    1,
  ],
  [
    'Music',
    'Which band recorded “Hotel California”?',
    ['The Eagles', 'Fleetwood Mac', 'The Doors', 'Lynyrd Skynyrd'],
    0,
  ],
  [
    'Music',
    'Who is known as the “Queen of Soul”?',
    ['Aretha Franklin', 'Whitney Houston', 'Diana Ross', 'Tina Turner'],
    0,
  ],
  ['Music', 'Which instrument does Yo-Yo Ma play?', ['Violin', 'Cello', 'Piano', 'Double bass'], 1],
  [
    'Music',
    'Who sang “Shape of You”?',
    ['Ed Sheeran', 'Sam Smith', 'Shawn Mendes', 'Charlie Puth'],
    0,
  ],
  [
    'Music',
    'Which band released “Smoke on the Water”?',
    ['Led Zeppelin', 'Deep Purple', 'Black Sabbath', 'AC/DC'],
    1,
  ],
  [
    'Music',
    'Who is the lead singer of Queen?',
    ['Elton John', 'Freddie Mercury', 'David Bowie', 'Mick Jagger'],
    1,
  ],
  [
    'Music',
    'Which artist is nicknamed “The Boss”?',
    ['Bruce Springsteen', 'Bon Jovi', 'Billy Joel', 'John Mellencamp'],
    0,
  ],
  ['Music', 'What genre is associated with Jay-Z?', ['Country', 'Hip-hop', 'Jazz', 'Rock'], 1],
  ['Music', 'Who sang “Rolling in the Deep”?', ['Beyoncé', 'Adele', 'Rihanna', 'Sia'], 1],
  [
    'Music',
    'Which instrument has 47 strings and a pedal?',
    ['Harp', 'Piano', 'Guitar', 'Cello'],
    0,
  ],
  ['Music', 'Who composed the “Four Seasons”?', ['Bach', 'Mozart', 'Vivaldi', 'Handel'], 2],
  [
    'Music',
    'Which band sang “Sweet Child O’ Mine”?',
    ['Aerosmith', 'Guns N’ Roses', 'Bon Jovi', 'Metallica'],
    1,
  ],
  [
    'Music',
    'Who is the best-selling female artist of all time?',
    ['Madonna', 'Rihanna', 'Taylor Swift', 'Whitney Houston'],
    0,
  ],
  [
    'Music',
    'Which country does the band BTS come from?',
    ['Japan', 'China', 'South Korea', 'Thailand'],
    2,
  ],
  ['Music', 'Who sang “Old Town Road”?', ['Post Malone', 'Lil Nas X', 'Drake', 'Kid Cudi'], 1],
  [
    'Music',
    'What does “a cappella” mean?',
    ['With guitar', 'Without instruments', 'With piano', 'Slowly'],
    1,
  ],
  [
    'Music',
    'Who is known as the “King of Rock and Roll”?',
    ['Elvis Presley', 'Chuck Berry', 'John Lennon', 'Little Richard'],
    0,
  ],
  [
    'Music',
    'Which singer has the most Grammy wins?',
    ['Beyoncé', 'Quincy Jones', 'Taylor Swift', 'Jay-Z'],
    0,
  ],
  ['Music', 'Which instrument is also a vegetable?', ['Trumpet', 'Oboe', 'Cornet', 'Trombone'], 2],
  [
    'Music',
    'Who sang “Purple Rain”?',
    ['Michael Jackson', 'Prince', 'David Bowie', 'Lenny Kravitz'],
    1,
  ],
  ['Music', 'Which classical composer became deaf?', ['Mozart', 'Bach', 'Beethoven', 'Chopin'], 2],
  [
    'Music',
    'What is the highest female singing voice?',
    ['Alto', 'Mezzo-soprano', 'Soprano', 'Contralto'],
    2,
  ],
  [
    'Music',
    'Who wrote “Bohemian Rhapsody”?',
    ['Freddie Mercury', 'Elton John', 'Paul McCartney', 'David Bowie'],
    0,
  ],
  [
    'Music',
    'Which rapper released “Lose Yourself”?',
    ['Jay-Z', 'Eminem', 'Kanye West', 'Drake'],
    1,
  ],
  ['Music', 'How many strings does a standard guitar have?', ['4', '5', '6', '7'], 2],
  [
    'Music',
    'Who sang “Shallow” with Bradley Cooper?',
    ['Ariana Grande', 'Lady Gaga', 'Beyoncé', 'Katy Perry'],
    1,
  ],
  [
    'Music',
    'Which genre did Elvis Presley popularize?',
    ['Jazz', 'Rock and roll', 'Blues', 'Country'],
    1,
  ],
  [
    'Music',
    'Which group sang “Dancing Queen”?',
    ['ABBA', 'The Bee Gees', 'Boney M', 'The Carpenters'],
    0,
  ],
  [
    'Music',
    'Who is the lead vocalist of Coldplay?',
    ['Chris Martin', 'Thom Yorke', 'Brandon Flowers', 'Matt Bellamy'],
    0,
  ],
  // ------------------------------ Food -----------------------------------
  ['Food', 'Which country is famous for sushi?', ['China', 'Thailand', 'Japan', 'Korea'], 2],
  [
    'Food',
    'What is the main ingredient in guacamole?',
    ['Tomato', 'Avocado', 'Pepper', 'Onion'],
    1,
  ],
  [
    'Food',
    'Which cheese is traditionally used on pizza?',
    ['Cheddar', 'Mozzarella', 'Swiss', 'Feta'],
    1,
  ],
  [
    'Food',
    'What is the most consumed fruit in the world?',
    ['Banana', 'Apple', 'Tomato', 'Mango'],
    0,
  ],
  ['Food', 'Which country invented pasta?', ['France', 'Italy', 'Greece', 'China'], 1],
  ['Food', 'What is the main ingredient in hummus?', ['Lentils', 'Chickpeas', 'Beans', 'Peas'], 1],
  ['Food', 'Which beverage contains caffeine?', ['Water', 'Orange juice', 'Coffee', 'Milk'], 2],
  ['Food', 'What is sushi wrapped in?', ['Seaweed', 'Rice paper', 'Lettuce', 'Soy sheets'], 0],
  [
    'Food',
    'Which fruit is known as the king of fruits?',
    ['Mango', 'Durian', 'Pineapple', 'Jackfruit'],
    1,
  ],
  ['Food', 'What is the main ingredient in chocolate?', ['Sugar', 'Cocoa', 'Milk', 'Caramel'], 1],
  ['Food', 'Which country is famous for tacos?', ['Spain', 'Argentina', 'Mexico', 'Peru'], 2],
  [
    'Food',
    'What is a croissant traditionally made from?',
    ['Puff pastry', 'Shortcrust', 'Bread dough', 'Choux'],
    0,
  ],
  ['Food', 'Which nut is used to make marzipan?', ['Peanut', 'Cashew', 'Almond', 'Walnut'], 2],
  ['Food', 'What is the main ingredient in a mojito?', ['Rum', 'Vodka', 'Tequila', 'Gin'], 0],
  ['Food', 'Which food is fermented cabbage?', ['Kimchi', 'Sauerkraut', 'Pickles', 'Salsa'], 1],
  [
    'Food',
    'What is the world’s most expensive spice?',
    ['Cinnamon', 'Saffron', 'Vanilla', 'Turmeric'],
    1,
  ],
  [
    'Food',
    'Which country consumes the most tea per person?',
    ['China', 'UK', 'Turkey', 'India'],
    2,
  ],
  [
    'Food',
    'What is the main ingredient in miso soup?',
    ['Soybean paste', 'Seaweed', 'Tofu only', 'Rice'],
    0,
  ],
  ['Food', 'Which fruit is a berry?', ['Strawberry', 'Banana', 'Watermelon', 'Tomato'], 3],
  ['Food', 'What is the main ingredient in pesto?', ['Basil', 'Cilantro', 'Mint', 'Parsley'], 0],
  ['Food', 'Which country invented french fries?', ['France', 'Belgium', 'USA', 'Netherlands'], 1],
  ['Food', 'What does “al dente” mean?', ['Soft', 'Firm to the bite', 'Overcooked', 'Cold'], 1],
  [
    'Food',
    'Which is a popular Indian street food?',
    ['Poutine', 'Pani puri', 'Falafel', 'Ramen'],
    1,
  ],
  [
    'Food',
    'What is the main ingredient in a carbonara sauce?',
    ['Tomato', 'Eggs and cheese', 'Cream only', 'Butter'],
    1,
  ],
  ['Food', 'Which country drinks the most coffee?', ['USA', 'Brazil', 'Finland', 'Italy'], 2],
  [
    'Food',
    'What is a “boba” in bubble tea?',
    ['Cheese foam', 'Tapioca pearls', 'Jelly cubes', 'Ice cream'],
    1,
  ],
  [
    'Food',
    'Which fish is used to make the most authentic sushi?',
    ['Salmon', 'Tuna', 'Sea bass', 'All of the above'],
    3,
  ],
  [
    'Food',
    'What is the main ingredient in mayonnaise?',
    ['Milk', 'Oil and eggs', 'Butter', 'Vinegar only'],
    1,
  ],
  ['Food', 'Which country is famous for paella?', ['Mexico', 'Portugal', 'Spain', 'Italy'], 2],
  ['Food', 'What is the main ingredient in tofu?', ['Rice', 'Soybeans', 'Lentils', 'Wheat'], 1],
  // ----------------------------- Technology ------------------------------
  [
    'Technology',
    'Who co-founded Apple with Steve Jobs?',
    ['Bill Gates', 'Steve Wozniak', 'Jeff Bezos', 'Tim Cook'],
    1,
  ],
  [
    'Technology',
    'What does “www” stand for?',
    ['World Wide Web', 'World Web Window', 'Wide World Web', 'Web World Wide'],
    0,
  ],
  ['Technology', 'Which company makes the iPhone?', ['Samsung', 'Google', 'Apple', 'OnePlus'], 2],
  [
    'Technology',
    'What does “RAM” stand for?',
    ['Random Access Memory', 'Read All Memory', 'Rapid Access Module', 'Random Allocated Memory'],
    0,
  ],
  [
    'Technology',
    'Which programming language is named after a snake?',
    ['Java', 'Python', 'Cobra', 'Rust'],
    1,
  ],
  [
    'Technology',
    'What is the most popular search engine?',
    ['Bing', 'Yahoo', 'Google', 'DuckDuckGo'],
    2,
  ],
  [
    'Technology',
    'What does “USB” stand for?',
    ['Universal Serial Bus', 'United Serial Bus', 'Universal System Bus', 'Universal Sync Base'],
    0,
  ],
  [
    'Technology',
    'Which social media platform was founded by Mark Zuckerberg?',
    ['Twitter', 'Instagram', 'Facebook', 'LinkedIn'],
    2,
  ],
  [
    'Technology',
    'What is the name of Google’s AI chatbot?',
    ['Siri', 'Gemini', 'Alexa', 'Cortana'],
    1,
  ],
  [
    'Technology',
    'Which company created the Windows operating system?',
    ['Apple', 'Microsoft', 'IBM', 'Dell'],
    1,
  ],
  [
    'Technology',
    'What does “AI” stand for?',
    [
      'Automated Intelligence',
      'Artificial Intelligence',
      'Advanced Interface',
      'Algorithmic Input',
    ],
    1,
  ],
  ['Technology', 'Which currency is a cryptocurrency?', ['Dollar', 'Bitcoin', 'Euro', 'Yen'], 1],
  [
    'Technology',
    'What is the name of the first web browser?',
    ['Chrome', 'Mosaic', 'Netscape', 'Safari'],
    1,
  ],
  ['Technology', 'Which company owns WhatsApp?', ['Google', 'Microsoft', 'Meta', 'Amazon'], 2],
  [
    'Technology',
    'What does “GPU” stand for?',
    [
      'Graphics Processing Unit',
      'General Processing Unit',
      'Graphics Power Unit',
      'Global Processing Unit',
    ],
    0,
  ],
  [
    'Technology',
    'Which operating system does a Mac run?',
    ['Windows', 'Linux', 'macOS', 'Android'],
    2,
  ],
  [
    'Technology',
    'Who is known as the father of computers?',
    ['Alan Turing', 'Charles Babbage', 'Bill Gates', 'Steve Jobs'],
    1,
  ],
  [
    'Technology',
    'What is the most popular programming language in 2024?',
    ['Java', 'C++', 'Python', 'JavaScript'],
    2,
  ],
  [
    'Technology',
    'Which company makes the PlayStation?',
    ['Nintendo', 'Microsoft', 'Sony', 'Sega'],
    2,
  ],
  [
    'Technology',
    'What does “HTML” stand for?',
    [
      'HyperText Markup Language',
      'HighText Machine Language',
      'Hyperlink Text Mode Language',
      'Home Tool Markup Language',
    ],
    0,
  ],
  [
    'Technology',
    'Which electric car company did Elon Musk lead?',
    ['Rivian', 'Tesla', 'NIO', 'BYD'],
    1,
  ],
  [
    'Technology',
    'What is the name of Amazon’s voice assistant?',
    ['Siri', 'Alexa', 'Google Assistant', 'Bixby'],
    1,
  ],
  [
    'Technology',
    'Which company created the Android OS?',
    ['Apple', 'Google', 'Samsung', 'Microsoft'],
    1,
  ],
  [
    'Technology',
    'What does “CPU” stand for?',
    [
      'Central Processing Unit',
      'Computer Personal Unit',
      'Core Processing Unit',
      'Central Program Utility',
    ],
    0,
  ],
  [
    'Technology',
    'Which video platform was founded in 2005?',
    ['Netflix', 'YouTube', 'Twitch', 'Vimeo'],
    1,
  ],
  [
    'Technology',
    'What is the name of Microsoft’s gaming console?',
    ['PlayStation', 'Xbox', 'Switch', 'Steam Deck'],
    1,
  ],
  [
    'Technology',
    'Which company makes the GPT models?',
    ['Google', 'OpenAI', 'Meta', 'Anthropic'],
    1,
  ],
  [
    'Technology',
    'What does “VPN” stand for?',
    [
      'Virtual Private Network',
      'Very Private Network',
      'Virtual Public Network',
      'Verified Personal Network',
    ],
    0,
  ],
  [
    'Technology',
    'Which is the largest tech company by market value?',
    ['Microsoft', 'Apple', 'Nvidia', 'Amazon'],
    2,
  ],
  [
    'Technology',
    'What is the name of the cloud service by Amazon?',
    ['Azure', 'AWS', 'GCP', 'Oracle Cloud'],
    1,
  ],
  // ------------------------- Batch 2 (to reach 500+) --------------------
  [
    'Geography',
    'Which country has the largest population in Africa?',
    ['Egypt', 'Nigeria', 'Ethiopia', 'Kenya'],
    1,
  ],
  [
    'Geography',
    'The Panama Canal connects which two oceans?',
    ['Atlantic & Indian', 'Atlantic & Pacific', 'Pacific & Arctic', 'Indian & Pacific'],
    1,
  ],
  ['Geography', 'What is the capital of Switzerland?', ['Zurich', 'Geneva', 'Bern', 'Basel'], 2],
  [
    'Geography',
    'Which is the largest country in South America?',
    ['Argentina', 'Peru', 'Colombia', 'Brazil'],
    3,
  ],
  [
    'Geography',
    'Which city is known as the Big Apple?',
    ['Los Angeles', 'New York City', 'Chicago', 'Boston'],
    1,
  ],
  [
    'Geography',
    'The Danube River flows through which continent?',
    ['Asia', 'Africa', 'Europe', 'South America'],
    2,
  ],
  ['Geography', 'What is the capital of Kenya?', ['Nairobi', 'Lagos', 'Accra', 'Addis Ababa'], 0],
  [
    'Geography',
    'Which country is the largest island nation?',
    ['Japan', 'Indonesia', 'Philippines', 'New Zealand'],
    1,
  ],
  [
    'Geography',
    'Mount Kilimanjaro is in which country?',
    ['Kenya', 'Tanzania', 'Uganda', 'Zimbabwe'],
    1,
  ],
  [
    'Geography',
    'What is the capital of Norway?',
    ['Stockholm', 'Helsinki', 'Oslo', 'Copenhagen'],
    2,
  ],
  [
    'Movies',
    'Who directed “Titanic” and “Avatar”?',
    ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Christopher Nolan'],
    0,
  ],
  [
    'Movies',
    'Which movie features the character Jack Dawson?',
    ['Avatar', 'Titanic', 'Inception', 'The Revenant'],
    1,
  ],
  [
    'Movies',
    'Who played Hermione Granger in the Harry Potter films?',
    ['Emma Stone', 'Emma Watson', 'Emma Roberts', 'Keira Knightley'],
    1,
  ],
  [
    'Movies',
    'Which film features the quote “I’ll be back”?',
    ['Terminator', 'RoboCop', 'Predator', 'Rambo'],
    0,
  ],
  [
    'Movies',
    'Who directed “La La Land”?',
    ['Damien Chazelle', 'David O. Russell', 'Greta Gerwig', 'Wes Anderson'],
    0,
  ],
  [
    'Movies',
    'Which animated studio made “Shrek”?',
    ['Pixar', 'DreamWorks', 'Illumination', 'Blue Sky'],
    1,
  ],
  [
    'Movies',
    'Who played Batman in “The Dark Knight”?',
    ['Christian Bale', 'Ben Affleck', 'Michael Keaton', 'Robert Pattinson'],
    0,
  ],
  [
    'Movies',
    'Which movie is about a girl named Matilda?',
    ['Nanny McPhee', 'Matilda', 'A Little Princess', 'Annie'],
    1,
  ],
  [
    'Movies',
    'Who directed “The Wizard of Oz”?',
    ['Victor Fleming', 'Frank Capra', 'Alfred Hitchcock', 'John Ford'],
    0,
  ],
  [
    'Movies',
    'Which movie series features the character Ethan Hunt?',
    ['James Bond', 'Mission Impossible', 'Bourne', 'John Wick'],
    1,
  ],
  [
    'Music',
    'Who sang “Despacito”?',
    ['Shakira', 'Luis Fonsi', 'Ricky Martin', 'Enrique Iglesias'],
    1,
  ],
  [
    'Music',
    'Which band sang “Don’t Stop Believin’”?',
    ['Journey', 'Bon Jovi', 'REO Speedwagon', 'Survivor'],
    0,
  ],
  [
    'Music',
    'Who is the lead singer of the Rolling Stones?',
    ['Mick Jagger', 'Keith Richards', 'Elton John', 'Rod Stewart'],
    0,
  ],
  [
    'Music',
    'Which song by Adele is about a past relationship?',
    ['Rolling in the Deep', 'Skyfall', 'Easy on Me', 'Hello'],
    3,
  ],
  [
    'Music',
    'What is the largest string instrument in an orchestra?',
    ['Cello', 'Viola', 'Double bass', 'Violin'],
    2,
  ],
  ['Music', 'Who sang “Single Ladies”?', ['Beyoncé', 'Rihanna', 'Nicki Minaj', 'Alicia Keys'], 0],
  [
    'Music',
    'Which group sings “Uptown Funk”?',
    ['Bruno Mars', 'Mark Ronson ft. Bruno Mars', 'Pharrell Williams', 'Daft Punk'],
    1,
  ],
  ['Music', 'Who composed the “Moonlight Sonata”?', ['Bach', 'Mozart', 'Beethoven', 'Chopin'], 2],
  [
    'Music',
    'Which rapper is known as “Slim Shady”?',
    ['Eminem', 'Dr. Dre', 'Snoop Dogg', '50 Cent'],
    0,
  ],
  [
    'Music',
    'Which instrument is most associated with jazz?',
    ['Saxophone', 'Violin', 'Sitar', 'Accordion'],
    0,
  ],
  [
    'Food',
    'What is the main ingredient in a traditional Italian risotto?',
    ['Rice', 'Pasta', 'Polenta', 'Barley'],
    0,
  ],
  ['Food', 'Which fruit is used to make wine?', ['Apples', 'Grapes', 'Berries', 'Plums'], 1],
  ['Food', 'What is the national dish of Japan?', ['Sushi', 'Ramen', 'Curry rice', 'Tempura'], 1],
  ['Food', 'Which cheese has holes?', ['Cheddar', 'Swiss', 'Mozzarella', 'Gouda'], 1],
  [
    'Food',
    'What is the main ingredient in a falafel?',
    ['Lentils', 'Chickpeas', 'Fava beans only', 'Tofu'],
    1,
  ],
  ['Food', 'Which country is famous for chocolate?', ['Belgium', 'Italy', 'France', 'Germany'], 0],
  [
    'Food',
    'What is the main ingredient in a classic margherita pizza sauce?',
    ['Tomato', 'Cream', 'Pesto', 'BBQ sauce'],
    0,
  ],
  [
    'Food',
    'Which vegetable is the main ingredient in French onion soup?',
    ['Potato', 'Onion', 'Leek', 'Garlic'],
    1,
  ],
  [
    'Food',
    'What is a “croque monsieur”?',
    ['A ham and cheese sandwich', 'A pastry', 'A soup', 'A dessert'],
    0,
  ],
  ['Food', 'Which fruit is dried to make raisins?', ['Grapes', 'Plums', 'Apricots', 'Cherries'], 0],
  [
    'Technology',
    'What does “Wi-Fi” stand for?',
    ['Wireless Fidelity', 'Wide Frequency', 'Wireless Frequency', 'Wired Fidelity'],
    0,
  ],
  [
    'Technology',
    'Which company makes the Galaxy phone?',
    ['Apple', 'Samsung', 'Xiaomi', 'Google'],
    1,
  ],
  [
    'Technology',
    'What is the most popular social media app by users?',
    ['Instagram', 'TikTok', 'Facebook', 'WhatsApp'],
    2,
  ],
  [
    'Technology',
    'Which operating system powers most smartphones?',
    ['iOS', 'Android', 'Windows', 'Symbian'],
    1,
  ],
  [
    'Technology',
    'What does “API” stand for?',
    [
      'Application Programming Interface',
      'Automated Program Input',
      'Applied Programming Index',
      'Application Process Integration',
    ],
    0,
  ],
  ['Technology', 'Which company owns Instagram?', ['Google', 'Meta', 'Microsoft', 'Snap'], 1],
  [
    'Technology',
    'What is the name of Apple’s virtual assistant?',
    ['Alexa', 'Siri', 'Gemini', 'Cortana'],
    1,
  ],
  ['Technology', 'Which language is used to style web pages?', ['HTML', 'CSS', 'Python', 'SQL'], 1],
  [
    'Technology',
    'What does “SSD” stand for?',
    ['Solid State Drive', 'Super Speed Disk', 'System Storage Device', 'Solid System Drive'],
    0,
  ],
  [
    'Technology',
    'Which company created the Java language?',
    ['Microsoft', 'Sun Microsystems', 'IBM', 'Oracle'],
    1,
  ],
];

const NEW_CATEGORIES = ['Geography', 'Movies', 'Music', 'Food', 'Technology'];

const existing = JSON.parse(readFileSync(join(root, 'src/data/trivia-questions.json'), 'utf8'));
const seen = new Set(existing.map((q) => q.question.toLowerCase()));
let added = 0;
for (const [category, question, options, answer] of NEW_QUESTIONS) {
  if (seen.has(question.toLowerCase())) {
    continue;
  }
  existing.push({ category, question, options, answer });
  seen.add(question.toLowerCase());
  added += 1;
}

const output = JSON.stringify(existing, null, 2) + '\n';
writeFileSync(join(root, 'src/data/trivia-questions.json'), output);
writeFileSync(join(root, 'server/src/data/trivia-questions.json'), output);

const byCategory = {};
for (const q of existing) {
  byCategory[q.category] = (byCategory[q.category] ?? 0) + 1;
}
console.log(
  `trivia: ${existing.length} questions (+${added}) across ${Object.keys(byCategory).length} categories: ${JSON.stringify(byCategory)}`
);
console.log(`new categories: ${NEW_CATEGORIES.join(', ')}`);
